var soap_stars = [
 {name:"Tracy Barlow"    ,age:37, program_rating:04, kill_count:05, lengh_of_service:14, looks:02},
 {name:"Dodger Savage"   ,age:26, program_rating:05, kill_count:01, lengh_of_service:06, looks:10},
 {name:"Debbie Dingle"   ,age:26, program_rating:04, kill_count:03, lengh_of_service:13, looks:07},
 {name:"Mick Cater"      ,age:36, program_rating:03, kill_count:00, lengh_of_service:01, looks:06},
 {name:"Robbie Roscoe"   ,age:19, program_rating:05, kill_count:01, lengh_of_service:01, looks:07},
 {name:"Holly Cunningham",age:18, program_rating:05, kill_count:00, lengh_of_service:17, looks:08},
 {name:"Cindy Williams"  ,age:14, program_rating:03, kill_count:00, lengh_of_service:04, looks:07},
 {name:"Billy Mitchell"  ,age:52, program_rating:03, kill_count:03, lengh_of_service:16, looks:04},
 {name:"Sonia Flower"    ,age:31, program_rating:03, kill_count:00, lengh_of_service:22, looks:07},
 {name:"Carol Jackson"   ,age:53, program_rating:03, kill_count:01, lengh_of_service:21, looks:09},
 {name:"Cain Dingle"     ,age:44, program_rating:04, kill_count:05, lengh_of_service:14, looks:07},
 {name:"Paddy Kirk"      ,age:44, program_rating:04, kill_count:00, lengh_of_service:17, looks:03},
 {name:"Marlon Dingle"   ,age:46, program_rating:04, kill_count:00, lengh_of_service:18, looks:03},
 {name:"Ashley Thomas"   ,age:60, program_rating:04, kill_count:09, lengh_of_service:18, looks:02},
 {name:"Carla Connor"    ,age:41, program_rating:04, kill_count:00, lengh_of_service:08, looks:07},
 {name:"Maria Connor"    ,age:31, program_rating:04, kill_count:00, lengh_of_service:14, looks:08},
 {name:"Norris Cole"     ,age:74, program_rating:04, kill_count:10, lengh_of_service:21, looks:01},
 {name:"Peter Barlow"    ,age:16, program_rating:04, kill_count:01, lengh_of_service:14, looks:06},
 {name:"Ste Hay"         ,age:28, program_rating:05, kill_count:02, lengh_of_service:08, looks:08},
 {name:"Mercedes McQeen" ,age:30, program_rating:05, kill_count:02, lengh_of_service:16, looks:09}
 ];